version: '3.7'
services:
    neo4j:
        image: neo4j:${NEO4J_VERSION}
        ports:
            - "${NEO4J_HTTP_PORT:-7474}:7474"
            - "${NEO4J_BOLT_PORT:-7687}:7687"
        environment:
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
            - NEO4J_apoc_trigger_enabled=true
            - NEO4J_dbms_security_authentication__providers=oidc-keycloak,native
            - NEO4J_dbms_security_authorization__providers=oidc-keycloak,native
            - NEO4J_dbms_security_oidc_keycloak_display__name=Keycloak
            - NEO4J_dbms_security_oidc_keycloak_.auth__flow=pkce
            - NEO4J_dbms_security_oidc_keycloak_well__known__discovery__uri=http://keycloak:8080/realms/my-realm/.well-known/openid-configuration
            - NEO4J_dbms_security_oidc_keycloak_auth__endpoint=http://127.0.0.1:8180/realms/my-realm/protocol/openid-connect/auth
            - NEO4J_dbms_security_oidc_keycloak_token__endpoint=http://127.0.0.1:8180/realms/my-realm/protocol/openid-connect/token
            - NEO4J_dbms_security_oidc_keycloak_params=client_id=neo4j-sso;response_type=code;scope=openid email roles
            - NEO4J_dbms_security_oidc_keycloak_audience=account
            - NEO4J_dbms_security_oidc_keycloak_issuer=http://127.0.0.1:8180/realms/my-realm
            - NEO4J_dbms_security_oidc_keycloak_client__id=neo4j-sso
            - NEO4J_dbms_security_oidc_keycloak_claims_username=preferred_username
            - NEO4J_dbms_security_oidc_keycloak_claims_groups=roles
        volumes:
            - "hume_neo4j_data:/data"
        profiles:
            - neo4j
    neo4j-config-cli:
        image: graphaware/neo4j-config-cli:1.3.0
        environment:
            - NEO4J_USER=neo4j
            - NEO4J_PASSWORD=password
            - NEO4J_URI=bolt://neo4j:7687
            - IMPORT_PATH=/config
        volumes:
            - "./resources/neo4j-config:/config"
        profiles:
            - neo4j
    keycloak:
        image: quay.io/keycloak/keycloak:17.0.0
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin123
            - KEYCLOAK_LOGLEVEL=INFO
            - ROOT_LOGLEVEL=INFO
        command:
            - start-dev
        ports:
            - "8180:8080"
        depends_on: 
            - postgres_keycloak
        restart: always
        profiles:
            - all
            - keycloak
    keycloak-config:
        image: adorsys/keycloak-config-cli:edge
        environment:
            - KEYCLOAK_URL=http://keycloak:8080
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin123
            - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
            - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=15s
            - IMPORT_PATH=/config
        volumes:
            - ./resources/keycloak-config:/config
        profiles:
            - keycloak
            - all
volumes:
    hume_keycloak_data:
    hume_neo4j_data:
      